package by.epam.tr.controller.command;

/**
 * 
 * A class containing the names of all program commands
 *
 */
public enum CommandName {
  AUTHORIZATION, NO_SUCH_COMMAND, REGISTRATION, EXIT, MAKE_ORDER, MAKE_PAYMENT, ADD_TO_CART, DELETE_FROM_CART, SHOW_CATALOG, SHOW_ORDER_LIST, SHOW_PAY_EVADERS_LIST, DELETE_ITEM, CHANGE_ITEM_DETAILS, CHANGE_DETAILS, ADD_TO_BLACKLIST, ADD_ITEM, SHOW_CART, GO_ADD_ITEM, GO_ADMIN_PROFILE, GO_AUTHORIZATION, GO_CHANGE_ITEMS_DETAILS, GO_CLIENT_PROFILE, GO_PAY, GO_REGISTRATION
}
